# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d0d200cccee9cdb5c78dd24566915ecd23562c3fd213271175877d7967accfdc3aae4b015c878cbec1d9904e87d46bb4f87e393a2ec2863e1ec2814748cc06d9

test:
  secret_key_base: 578b107b97db73d73c106956ee793a702710c6ef39bf16dfb42b8de8fc1a21b6d531715f7d510a05880c47e48e0dc0e5449e3b4aae164c08427d7434c846cec4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
